Add second floor
Andreybest/ppc-vr-tour pull request #2
Opened 2020-01-08 16:21 UTC by klas3

2020-01-09 21:25 UTC, Andreybest requested changes
Everything is good, but many arrows need repositioning.
And 'director'sOffice.jpg' should be renamed to 'directorsWaitingRoom.jpg'.

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallRight2" data-thumb="#arrow" position="-11.8 -2.8 9.1" rotation="-70 170 -40"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallRight1" data-thumb="#arrow" position="-0.7 -4.7 11" rotation="-90 80 92"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallRight1" data-thumb="#arrow" position="8.2 -2.7 0.6" rotation="0.2 -80 -5"></a-entity>
Needs small remove

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneAudience217" data-thumb="#arrow" position="4.5 -4.3 -3.3" rotation="0.2 -50 10"></a-entity>
Needs small remove

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneAudience213" data-thumb="#arrow" position="4.2 -5 11.3" rotation="-80 -170 80"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallMiddle1" data-thumb="#arrow" position="15.3 -3.7 2.8" rotation="0.2 -100 5"></a-entity>
Needs small remove

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallMiddle2" data-thumb="#arrow" position="-1 -5.2 10.1" rotation="-30 180 0"></a-entity>
Needs small remove

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallMiddle2" data-thumb="#arrow" position="6.1 -3.8 -13.4" rotation="40 -30 25"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallMiddle2" data-thumb="#arrow" position="10.6 -2.7 9.8" rotation="-70 -70 0"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallLeft2" data-thumb="#arrow" position="-8.2 -4.1 -9.2" rotation="-110 -130 180"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallLeft3" data-thumb="#arrow" position="-8.1 -4.1 -14.1" rotation="-110 -188 180"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneHallLeft4" data-thumb="#arrow" position="-8 -4.1 -10.4" rotation="-103.2 -188 180"></a-entity>
Hard to click for mobile users

2020-01-09 21:25 UTC, Andreybest commented on secondFloor.html
> +                    <a-entity template="src: #link" data-src="sceneAudience201Hall1" data-thumb="#arrow" position="-10 -5 0" rotation="-110 -93 180"></a-entity>
Needs small remove

2020-01-09 21:34 UTC, Andreybest commented
Also forgot to mention, index.html needs a link to 2 floor.

2020-01-11 16:22 UTC, klas3 commented
Problematic arrows has been fixed, also all floors-connecting links has been added.

2020-01-11 16:53 UTC, Andreybest requested changes
All good!
The only thing, you forgot to change arrow in room 218.
And I requested to rename to 'directorsWaitingRoom.jpg', not to 'director'sWaitingRoom.jpg'.
' is a big no no in file namings.
Fix this issues and Im merging this PR to master.

2020-01-11 16:53 UTC, Andreybest commented on index.html
> +				<img id="secondFloorUpStairs" crossorigin="anonymous" src="img/floorsIcons/secondFloorUpStairs.jpg">
Remove duplicating links

2020-01-11 16:53 UTC, Andreybest commented on index.html
> +					<a-entity link="href: secondFloor.html;" template="src: #link" data-src="" data-thumb="#secondFloorUpStairs" position="6.000 -2.000 -10.000" rotation="0.000 -15.000 0.000" scale="1.500 1.500 0.0
Remove duplicating links

2020-01-11 17:19 UTC, Andreybest commented
All good, thanks for a work!

2020-01-11 17:23 UTC, merged